language: node_js
node_js:
  - "4.2"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - rvm install 2.2.2
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
install:
  - bundle install --path vendor/bundle
  - npm install
script:
  - npm run build-travis
cache:
  directories:
    - node_modules
    - vendor/bundle
