version: 2

jobs:

  build:
    working_directory: ~/design-system

    docker:
      - image: ncino/ci-sfdx:latest

    environment:
      DEPLOY_TOOLKIT: ~/pyhton-deploy-toolkit
      DEPENDENCY_LOG: /tmp/dependency.log
      FAILURE_FILE: /tmp/build_failures.txt
      LOG_LEVEL: DEBUG
      TESTING_LOG: /tmp/testing.log

    steps:
      - checkout

      - run:
          name: Checkout python-deploy-toolkit
          command: git clone git@github.com:ncino/python-deploy-toolkit.git $DEPLOY_TOOLKIT

      - run:
          name: Install python-deploy-toolkit
          command: cd $DEPLOY_TOOLKIT && npm install -g

      - run:
          name: sfdeploy -d report_build_info
          command: sfdeploy -d report_build_info -lt off || ( touch $FAILURE_FILE && exit 1 )

      - run:
          name: sfdeploy -d npm_install
          command: sfdeploy -d npm_install -s ui/ -lt file -ll $LOG_LEVEL -lp $DEPENDENCY_LOG -ci || ( touch $FAILURE_FILE && exit 1 )

      - run:
          name: npm run dist
          command: npm run dist || ( touch $FAILURE_FILE && exit 1 )

      - deploy:
          name: Build the release and deploy to github
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              build-release
            fi

      - run:
          name: Build notifications
          command: $DEPLOY_TOOLKIT/scripts/build_notifications.py
          when: always
